#!/usr/bin/env python
# This file is Python 2 compliant.

import os, sys

_srcdir = '../../' # 设置vpcore的父目录为源码目录(下面包含了 vpcore, you-get等项目)
if getattr(sys, 'frozen', False):
    # The application is frozen
    _filepath = os.path.dirname(os.path.realpath(sys.executable))
else:
    # The application is not frozen
    # Change this bit to match where you store your data files:
    _filepath = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(1, os.path.join(_filepath, _srcdir))

if sys.version_info[0] == 3:
    import vpcore
    if __name__ == '__main__': #因为当前为执行，所以__name__为 '__main__'
    
        print('\n##### youku ####### http://v.youku.com/v_show/id_XMTI5MjcwNDI5Mg==.html?from=y1.2-2.4.2')
        print(vpcore.mycall('http://v.youku.com/v_show/id_XMTI5MjcwNDI5Mg==.html?from=y1.2-2.4.2')+'\n\n\n')
    
    
       
        print('\n##### iqiyi ####### http://m.iqiyi.com/v_19rro2q4mg.html')
        print(vpcore.mycall('http://m.iqiyi.com/v_19rro2q4mg.html')+'\n\n\n')
        # 2015.9.25 8:58->16:11 http://cache.m.iqiyi.com/jp/tmts/347655300/be63d714afd883b930f81679d9f05d5f/?platForm=h5&rate=1&tvid=347655300&vid=be63d714afd883b930f81679d9f05d5f&cupid=qc_100001_100102&type=m3u8&qyid=a889e164b02f494698d78af0947b750c&nolimit=0&src=d846d0c32d664d32b6b54ea48997a589&sc=ed67e08a784a3b8fff12f8f1f9d1aaac&__refI=&qd_wsz=MF85MDA=&t=1443142642342&__jsT=sijsc&callback=jsonp1    
        #2015.10.28             http://cache.m.iqiyi.com/jp/tmts/347655300/be63d714afd883b930f81679d9f05d5f/?platForm=h5&rate=1&tvid=347655300&vid=be63d714afd883b930f81679d9f05d5f&cupid=qc_100001_100102&type=m3u8&qyid=c9007b8fae94b15a849a9825789b3d87&nolimit=0&qd_jsin=aGFoYQ%3D%3D&src=d846d0c32d664d32b6b54ea48997a589&sc=ac5a5b3bc7f64be09b55b9e292bb5e8d&__refI=http%253A%252F%252Fm.iqiyi.com%252Fv_19rro2q4mg.html%253B1%253B%2526tim%253D1446457257411&qd_wsz=LThfMzI%3D&t=1446457257404&__jsT=sijsc&callback=jsonp1

        
        print('\n##### letv #######  http://www.letv.com/ptv/vplay/23264743.html')
        #'''
        #stream_id: 720p, 1080p, 350, 1300, 1000
        #'''
        #print(vpcore.mycall('http://www.letv.com/ptv/vplay/23264743.html', '720p')+'\n\n\n') 


        
        print('\n##### sohu ####### http://tv.sohu.com/20150811/n418543855.shtml')
        #print(vpcore.mycall('http://tv.sohu.com/20150811/n418543855.shtml')+'\n\n\n')        
        
        
        
        
        
        print('\n###### fushion ########  http://www.fun.tv/vplay/g-200180')
        print(vpcore.mycall('http://www.fun.tv/vplay/g-200180')+'\n\n\n')
       
else:
    from you_get.util import log
    log.wtf("""
    [Fatal] Python 3 is required.
    If Python 3 is already installed on your machine, try to run this script using 'python3 you-get'.""")
