#!/usr/bin/env python
# This file is Python 2 compliant.

import os, sys

_srcdir = '../../' # 设置vpcore的父目录为源码目录(下面包含了 vpcore, you-get等项目)
if getattr(sys, 'frozen', False):
    # The application is frozen
    _filepath = os.path.dirname(os.path.realpath(sys.executable))
else:
    # The application is not frozen
    # Change this bit to match where you store your data files:
    _filepath = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(1, os.path.join(_filepath, _srcdir))

if sys.version_info[0] == 3:
    import vpcore
    if __name__ == '__main__': #因为当前为执行，所以__name__为 '__main__'
    
        print('##### youku ####### http://v.youku.com/v_show/id_XMTI5MjcwNDI5Mg==.html?from=y1.2-2.4.2')
        print(vpcore.mycall('http://v.youku.com/v_show/id_XMTI5MjcwNDI5Mg==.html?from=y1.2-2.4.2')+'\n')
        
        print('##### iqiyi ####### http://www.iqiyi.com/v_19rroheauw.html')
        print(vpcore.mycall('http://www.iqiyi.com/v_19rroheauw.html')+'\n')

        print('##### letv #######  http://www.letv.com/ptv/vplay/23264743.html')
        '''
        stream_id: 720p, 1080p, 350, 1300, 1000
        '''
        print(vpcore.mycall('http://www.letv.com/ptv/vplay/23264743.html', '720p')+'\n')  

        print('##### sohu ####### http://tv.sohu.com/20150811/n418543855.shtml')
        print(vpcore.mycall('http://tv.sohu.com/20150811/n418543855.shtml')+'\n')        
       
else:
    from you_get.util import log
    log.wtf("""
    [Fatal] Python 3 is required.
    If Python 3 is already installed on your machine, try to run this script using 'python3 you-get'.""")
