#!/usr/bin/env python
# This file is Python 2 compliant.

import os, sys

_srcdir = '../../' # 设置vpcore的父目录为源码目录(下面包含了 vpcore, you-get等项目)
if getattr(sys, 'frozen', False):
    # The application is frozen
    _filepath = os.path.dirname(os.path.realpath(sys.executable))
else:
    # The application is not frozen
    # Change this bit to match where you store your data files:
    _filepath = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(1, os.path.join(_filepath, _srcdir))

if sys.version_info[0] == 3:
    import vpcore #导入 vpcore包(含__init__.py文件)，继而被导入 __main__.py模块中的相关内容。
    if __name__ == '__main__': #因为当前为执行，所以__name__为 '__main__'
        vpcore.main(repo_path=_filepath) # 调用vpcore包的main函数，即__main__.py模块中的main函数。
else:
    from you_get.util import log
    log.wtf("""
    [Fatal] Python 3 is required.
    If Python 3 is already installed on your machine, try to run this script using 'python3 you-get'.""")
